logging.level.org.zalando.logbook: INFO
filmorate:
  CINEMA_INVENTION_DATE: "1895-12-28"
  server:
    error:
      include-message: always

spring:
  #  sql:
  #    init:
  #      mode: always
  #      schema-locations: classpath:schema.sql
  #      data-locations: classpath:data.sql
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev