logging.level.org.zalando.logbook: INFO
filmorate:
  CINEMA_INVENTION_DATE: "1895-12-28"
  server:
    error:
      include-message: always

spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev